### ISSUE TITLE
Exception in thread "AppKit Thread"

### ISSUE THREAD

**Issue by ghost** [jcefmaven/jcefsampleapp#7]
Always wenn the window is focused, I see the error `Exception in thread "AppKit Thread"` without any additional information or stacktrace.

```
Test report generated by JCefSampleApp
**Tag**
122.1.10

**OS (linux/windows/macosx)**
macosx

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
macOS 14.5 (14.5)

**Arch (amd64/i386/arm64/arm)**
amd64

**Report as working? (Y/N)**
<Y/N>

**Did you test with the official sample app? (Y/N)**
Y
```

**Comment by FriwiDev** [comment]
Sorry for the late reply. I will close this issue for now, as no one else reported this issue in the past months. If it still persists, try asking in the jcef online communities. This is most likely an issue related to jcef and not this maven bindings (or the sample app).
